server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway
    zipkin:
      base-url: http://zipkin9000.com:9000/
      sleuth:
        sampler:
          percentage: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
#  ignored-services: microservicecloud-dept
  ignored-services: "*"
  prefix: /king
  routes:
#    mydept.serviceId: microservicecloud-dept
    mydept.serviceId: microservicecloud-config-dept-client
    mydept.path: /mydept/**

info:
  app.name: king-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$